#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

runlevel=default
for arg in $(cat /proc/cmdline); do
    if [ -d /etc/runit/runsvdir/"$arg" ]; then
        echo "Runlevel detected: '$arg' (via kernel cmdline)"
        runlevel="$arg"
    fi
done

runsvchdir "$runlevel"

[ -x /etc/runit/rc.startup.local ] && /etc/runit/rc.startup.local

exec env - PATH=$PATH \
runsvdir -P /var/service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
